# This is a basic workflow to help you get started with Actions

name: Sphinx Make Html

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "HW2" branch
  push:
    branches: [ "HW2" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9
 
      - name: Install dependencies
        run: |
          python -m pip install -U sphinx
          python -m pip install sphinx-rtd-theme
          # python -m pip install sphinxcontrib-apidoc
          python -m pip install sphinx-autoapi
        
      - name: Run Sphnix Build
        run: cd docs/ && make html
        
      - uses: stefanzweifel/git-auto-commit-action@v4

